name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build e Testes (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Executar testes de integracao
        run: |
          python -c "import paladino; print('Script paladino.py validado com sucesso!')"

  deploy:
    name: Deploy (CD)
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Simular Deploy de Producao
        run: |
          echo "Publicando versao aprovada no ambiente de producao..."
          echo "Status: Deploy finalizado com sucesso!"
