name: Continuous Delivery

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Executar Testes de CI
        run: |
          echo "Testando aplicacao e integrando codigo..."
          python -c "print('Testes concluidos com sucesso!')"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Executar Deploy de CD
        run: |
          echo "Realizando implantacao continua..."
          echo "Deploy realizado com sucesso!"
